// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {pgxpool} from '../models';
import {pgx} from '../models';
import {pgconn} from '../models';
import {database} from '../models';

export function Acquire(arg1:context.Context):Promise<pgxpool.Conn>;

export function AcquireAllIdle(arg1:context.Context):Promise<Array<pgxpool.Conn>>;

export function AcquireFunc(arg1:context.Context,arg2:any):Promise<void>;

export function Begin(arg1:context.Context):Promise<pgx.Tx>;

export function BeginTx(arg1:context.Context,arg2:pgx.TxOptions):Promise<pgx.Tx>;

export function Close():Promise<void>;

export function Config():Promise<pgxpool.Config>;

export function CopyFrom(arg1:context.Context,arg2:pgx.Identifier,arg3:Array<string>,arg4:pgx.CopyFromSource):Promise<number>;

export function Exec(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<pgconn.CommandTag>;

export function GetQueue():Promise<Array<database.Track>>;

export function Ping(arg1:context.Context):Promise<void>;

export function Query(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<pgx.Rows>;

export function QueryRow(arg1:context.Context,arg2:string,arg3:Array<any>):Promise<pgx.Row>;

export function RemoveTrack(arg1:number):Promise<void>;

export function Reset():Promise<void>;

export function SendBatch(arg1:context.Context,arg2:pgx.Batch):Promise<pgx.BatchResults>;

export function Stat():Promise<pgxpool.Stat>;
