// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Acquire(arg1) {
  return window['go']['database']['Database']['Acquire'](arg1);
}

export function AcquireAllIdle(arg1) {
  return window['go']['database']['Database']['AcquireAllIdle'](arg1);
}

export function AcquireFunc(arg1, arg2) {
  return window['go']['database']['Database']['AcquireFunc'](arg1, arg2);
}

export function Begin(arg1) {
  return window['go']['database']['Database']['Begin'](arg1);
}

export function BeginTx(arg1, arg2) {
  return window['go']['database']['Database']['BeginTx'](arg1, arg2);
}

export function Close() {
  return window['go']['database']['Database']['Close']();
}

export function Config() {
  return window['go']['database']['Database']['Config']();
}

export function CopyFrom(arg1, arg2, arg3, arg4) {
  return window['go']['database']['Database']['CopyFrom'](arg1, arg2, arg3, arg4);
}

export function Exec(arg1, arg2, arg3) {
  return window['go']['database']['Database']['Exec'](arg1, arg2, arg3);
}

export function GetQueue() {
  return window['go']['database']['Database']['GetQueue']();
}

export function Ping(arg1) {
  return window['go']['database']['Database']['Ping'](arg1);
}

export function Query(arg1, arg2, arg3) {
  return window['go']['database']['Database']['Query'](arg1, arg2, arg3);
}

export function QueryRow(arg1, arg2, arg3) {
  return window['go']['database']['Database']['QueryRow'](arg1, arg2, arg3);
}

export function Reset() {
  return window['go']['database']['Database']['Reset']();
}

export function SendBatch(arg1, arg2) {
  return window['go']['database']['Database']['SendBatch'](arg1, arg2);
}

export function Stat() {
  return window['go']['database']['Database']['Stat']();
}
