system_binary(
    name="wails",
    binary_name="wails",
    fingerprint=r"v(19|[2-9][0-9])\..*\..*",
    fingerprint_args=["--version"],
)

run_shell_command(
    name="dev",
    command="wails dev"
)
